spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:./files/lavsource-bilibili-server;auto_server=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect

# noinspection SpringBootApplicationYaml
lavender:
  lavsource:
    server-name: bilibili

logging:
  level:
    de.honoka.lavender.lavsource.bilibili.mapper: debug